# Site settings
title: Thought in Motion 
email: mitchell.gordon95@gmail.com 
description: Mitchell Gordon's personal site.
baseurl: "" # the subpath of your site
url: "http://mitchgordon.me" # the base hostname & protocol for your site
twitter_username: megamitch95 
github_username: mitchellgordon95 

# Build settings
markdown: kramdown
